### PR TITLE
Include epoch microseconds in DT comparison methods. Closes #156

### LINKED ISSUE #156: Equality Comparison (and Others) Disregard Microseconds
The equality operators (e.g. `__eq__`) and other properties (e.g. `.epoch`) seem to ignore + truncate microseconds:

```python
In [2]: m1, m2 = maya.now(), maya.now()

In [3]: m1
Out[3]: <MayaDT epoch=1527031930.399905>

In [4]: m2
Out[4]: <MayaDT epoch=1527031930.399909>

In [5]: m1 == m2
Out[5]: True

In [6]: m1.datetime() == m2.datetime()
Out[6]: False

In [7]: m1.epoch
Out[7]: 1527031930
```

Is this microsecond truncation behavior intentional? It seems to disagree with `datetime's` microsecond treatment, with the `__repr__` of `MayaDT` itself, and with other `MayaDT` methods (e.g. `.datetime()`, `. iso8601()`, and of course `.microsecond`)

Thanks for this package!

### PR DESCRIPTION
**Pull request by timofurrer**

### CODE REVIEW

**Comment by kennethreitz** [comment]
This was originally done intentionally. Please make careful considerations before making this change.

**Comment by kennethreitz** [comment]
e.g. two nows generated “apparently” simultaneously, then compared equal.

I agree the microseconds are a better design decision.

**Comment by kennethreitz** [comment]
This is a major design change, though, and warrants a minor (or maybe even major) version bump.

**Comment by timofurrer** [comment]
> This was originally done intentionally

What was the reason for that?

> e.g. two nows generated “apparently” simultaneously, then compared equal.

Well, I hope no one bet one the that. It could easily happen that *two nows generated “apparently” simultaneously* would led to two datetimes with a different second and therefore not evaluate equal.

> This is a major design change, though, and warrants a minor (or maybe even major) version bump.

That's right. The question even is if internally we should calculate with the **total microseconds** after the epoch start to avoid floating point numbers.

**Pull request closed without merging**
